### PR TITLE
User/cameron jung/#159

### PR DESCRIPTION
**Pull request by CameronJung**
This will make it so that when a new review is sent to the backend, it will carry with it an array of ratings.
I also moved the positions of some of the ratings components to places that I think make more sense.
Closes issue #159

### CODE REVIEW

**Comment by LukeBMorrow** [comment]
Having the ratings at the bottom makes it not initially visible on long reviews (an example can be seen on book1's reviews). I would suggest putting them somewhere above the review's content.

**Comment by CameronJung** [comment]
I moved the ratings component back. I think as a team we need to have an in-depth discussion regarding the placement of such components. My line of reasoning is that the creation of a review should be primarily about the review, not the ratings and thus the review should be given prominent positioning. However, there are clearly other ways of looking at this matter with their own pros and cons. To figure out what the best option is will require a proper discussion when we have more time.

**Comment by LukeBMorrow** [comment]
Apologies, I believe I was unclear. The rating placement on the create review section is fine on the bottom. It's the rating on the focused review display where it's inconvenient in some situations.

**Comment by CameronJung** [comment]
I moved the ratings components again, see the latest commit message for details

**Review by LukeBMorrow — APPROVED** [review]
Looks good

**Pull request merged**
