### PR TITLE
Made separate files for frontend and backend testing

### LINKED ISSUE #104: Make separate files for frontend and backend workflow

### PR DESCRIPTION
**Pull request by gurtejboparai**
This should close #104

### CODE REVIEW

**Comment by gurtejboparai** [comment]
Someone needs to approve pull request #103 for it to be merged. After that frontend_testing will be successful as it has the required code.

**Comment by LukeBMorrow** [comment]
Should there be a front end npm task called `test`? It seems to  be failing because that task is missing

**Comment by gurtejboparai** [comment]
The front end tests pull request needs to be merged first , that has a task named test. Then U can run the checks again and it should work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gurtejboparai** [comment]
I will pull the code updated code from main again and then commit.

**Pull request merged**
