### PR TITLE
User/cameron jung/#209

### LINKED ISSUE #209: Create a single point of truth for the list of genres
The list of genres is used in multiple files as read only data. It would be wise to put this data into a single point of truth.

### PR DESCRIPTION
**Pull request by CameronJung**
Changed implementation to use front end storage
- The new implementation has 2 accessors same as the original one for the entire genre list and another that won't include "Overall"
- All new genre based implementation should use these methods
- changed all files (to the best of my knowledge) using a hardcoded genre list to use these storage accessors through computed variables
- this closes #209

### CODE REVIEW

**Comment by CameronJung** [comment]
It looks like our tests don't like the fact that genres is computed, I'll have to change the computed variables back into regular vue variables that are initialized by a hook. I started doing something else though. Hopefully I can get to this later this afternoon.

**Comment by LukeBMorrow** [comment]
If I'm remembering correctly, you have to setup the store getters inside the test to get it to work as expected.

**Comment by CameronJung** [comment]
alright I'll try that thanks

**Comment by CameronJung** [comment]
Yup that works, although it doesn't seem like it works if the fake store on the tests uses data() instead of state().

**Review by LukeBMorrow — APPROVED** [review]
Looks good

**Pull request merged**
